"""Notebook data catalog utilities."""

from __future__ import annotations

import csv
from dataclasses import asdict, dataclass
from pathlib import Path

from floodrisk.ml.training_schema import validate_training_table_schema


@dataclass(frozen=True)
class NotebookDataAsset:
    """Expected data/report asset for notebook exploration."""

    asset_id: str
    label: str
    relative_path: str
    category: str
    required_for_eda: bool
    description: str

    def as_dict(self) -> dict[str, str | bool]:
        """Return asset metadata as a dictionary."""

        return asdict(self)


@dataclass(frozen=True)
class NotebookDataCatalogEntry:
    """Catalog entry for one data/report asset."""

    asset: NotebookDataAsset
    exists: bool
    file_size_bytes: int
    row_count: int | None
    explorable: bool

    @property
    def status(self) -> str:
        """Return asset status."""

        if self.explorable:
            return "explorable"
        if self.exists:
            return "available_not_explorable"
        return "missing"

    @property
    def blocks_eda(self) -> bool:
        """Return True if missing asset blocks the initial EDA milestone."""

        return self.asset.required_for_eda and not self.explorable

    def as_dict(self) -> dict[str, str | int | bool | dict[str, str | bool] | None]:
        """Return catalog entry as a dictionary."""

        return {
            "asset": self.asset.as_dict(),
            "exists": self.exists,
            "file_size_bytes": self.file_size_bytes,
            "row_count": self.row_count,
            "explorable": self.explorable,
            "status": self.status,
            "blocks_eda": self.blocks_eda,
        }


@dataclass(frozen=True)
class NotebookDataCatalogSummary:
    """Notebook data catalog summary."""

    entries: list[NotebookDataCatalogEntry]

    @property
    def asset_count(self) -> int:
        """Return number of cataloged assets."""

        return len(self.entries)

    @property
    def available_count(self) -> int:
        """Return number of existing assets."""

        return sum(1 for entry in self.entries if entry.exists)

    @property
    def explorable_count(self) -> int:
        """Return number of explorable assets."""

        return sum(1 for entry in self.entries if entry.explorable)

    @property
    def missing_count(self) -> int:
        """Return number of missing assets."""

        return sum(1 for entry in self.entries if not entry.exists)

    @property
    def blocking_eda_count(self) -> int:
        """Return number of missing assets that block EDA."""

        return sum(1 for entry in self.entries if entry.blocks_eda)

    @property
    def ready_for_eda(self) -> bool:
        """Return True if required EDA assets are available."""

        return self.blocking_eda_count == 0

    def as_dict(self) -> dict[str, int | bool | list[dict]]:
        """Return catalog summary as a dictionary."""

        return {
            "asset_count": self.asset_count,
            "available_count": self.available_count,
            "explorable_count": self.explorable_count,
            "missing_count": self.missing_count,
            "blocking_eda_count": self.blocking_eda_count,
            "ready_for_eda": self.ready_for_eda,
            "entries": [entry.as_dict() for entry in self.entries],
        }


NOTEBOOK_DATA_ASSETS = (
    NotebookDataAsset(
        asset_id="sample_locations",
        label="Sample Malaysia locations",
        relative_path="data/samples/sample_malaysia_locations.csv",
        category="sample",
        required_for_eda=True,
        description="Small demo dataset for initial tabular EDA.",
    ),
    NotebookDataAsset(
        asset_id="weather_summary",
        label="Weather risk signal summary",
        relative_path="reports/weather_risk_signal_summary.json",
        category="weather",
        required_for_eda=True,
        description="Weather signal summary generated by the Phase 2 pipeline.",
    ),
    NotebookDataAsset(
        asset_id="weather_validation",
        label="Weather pipeline validation report",
        relative_path="reports/weather_pipeline_validation.md",
        category="weather",
        required_for_eda=False,
        description="Weather pipeline validation notes.",
    ),
    NotebookDataAsset(
        asset_id="geospatial_artifact_plan",
        label="Geospatial artifact plan",
        relative_path="reports/geospatial_artifact_plan.md",
        category="geospatial",
        required_for_eda=False,
        description="Planned geospatial boundary artifacts.",
    ),
    NotebookDataAsset(
        asset_id="geospatial_validation",
        label="Geospatial validation report",
        relative_path="reports/geospatial_validation_report.md",
        category="geospatial",
        required_for_eda=True,
        description="Current geospatial readiness report.",
    ),
    NotebookDataAsset(
        asset_id="dataset_readiness",
        label="Dataset readiness report",
        relative_path="reports/dataset_readiness_report.md",
        category="readiness",
        required_for_eda=True,
        description="Current dataset readiness status for ML planning.",
    ),
    NotebookDataAsset(
        asset_id="training_schema",
        label="Training table schema report",
        relative_path="reports/training_table_schema_report.md",
        category="ml_readiness",
        required_for_eda=True,
        description="Schema readiness report for future model-training table.",
    ),
    NotebookDataAsset(
        asset_id="notebook_environment",
        label="Notebook environment report",
        relative_path="reports/notebook_environment_report.md",
        category="notebook",
        required_for_eda=True,
        description="Notebook environment dependency readiness.",
    ),
    NotebookDataAsset(
        asset_id="initial_eda_report",
        label="Initial EDA report",
        category="eda",
        relative_path="reports/initial_eda_report.md",
        description="Generated initial EDA summary report.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="feature_table_plan",
        label="Feature table generation plan",
        category="ml_readiness",
        relative_path="reports/feature_table_plan.md",
        description="Future training feature-table generation plan.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="feature_table_builder_dry_run",
        label="Feature table builder dry run",
        category="ml_readiness",
        relative_path="reports/feature_table_builder_dry_run.md",
        description="Dry-run report for future training table generation.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="target_label_source_plan",
        label="Target label source plan",
        category="ml_readiness",
        relative_path="reports/target_label_source_plan.md",
        description="Target label source requirements and candidate plan.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="ml_training_readiness_report",
        label="ML training readiness gate",
        category="ml_readiness",
        relative_path="reports/ml_training_readiness_report.md",
        description="Combined gate report for real supervised ML readiness.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="target_label_source_evaluation",
        label="Target label source evaluation",
        category="ml_readiness",
        relative_path="reports/target_label_source_evaluation.md",
        description="Scorecard for future flood occurrence target-label sources.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="target_source_manifest",
        label="Target source candidate manifest",
        category="ml_readiness",
        relative_path="configs/target_source_candidates.json",
        description="Candidate registry for future target-label data sources.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="target_source_manifest_report",
        label="Target source manifest report",
        category="ml_readiness",
        relative_path="reports/target_source_manifest_report.md",
        description="Validation report for the target source candidate manifest.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="target_event_source_schema",
        label="Target event source schema report",
        category="ml_readiness",
        relative_path="reports/target_event_source_schema_report.md",
        description="Schema validation report for future historical flood-event labels.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="target_event_source_template",
        label="Historical flood event target template",
        category="ml_readiness",
        relative_path="templates/targets/historical_flood_events_template.csv",
        description="Tracked CSV template for future historical flood-event labels.",
        required_for_eda=False,
    ),
    NotebookDataAsset(
        asset_id="model_training_table",
        label="Model-ready training table",
        relative_path="data/processed/model_training/training_features.csv",
        category="ml_training",
        required_for_eda=False,
        description="Future model-ready feature table. Not required for initial EDA.",
    ),
)


def list_notebook_data_assets() -> list[NotebookDataAsset]:
    """Return known notebook data assets."""

    return list(NOTEBOOK_DATA_ASSETS)


def _csv_row_count(path: Path) -> int | None:
    """Return CSV row count when possible."""

    if path.suffix.lower() != ".csv" or not path.exists():
        return None

    with path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        return sum(1 for _ in reader)


def _asset_explorable(project_root: Path, asset: NotebookDataAsset) -> bool:
    """Return True if an asset can be used safely for notebook exploration."""

    path = project_root / asset.relative_path

    if not path.exists():
        return False

    if asset.asset_id == "model_training_table":
        return validate_training_table_schema(path).is_training_ready

    return True


def build_notebook_data_catalog(project_root: Path) -> NotebookDataCatalogSummary:
    """Build notebook data catalog summary."""

    entries = []

    for asset in NOTEBOOK_DATA_ASSETS:
        path = project_root / asset.relative_path
        exists = path.exists()

        entries.append(
            NotebookDataCatalogEntry(
                asset=asset,
                exists=exists,
                file_size_bytes=path.stat().st_size if exists else 0,
                row_count=_csv_row_count(path),
                explorable=_asset_explorable(project_root, asset),
            )
        )

    return NotebookDataCatalogSummary(entries=entries)


def render_notebook_data_catalog_report(
    summary: NotebookDataCatalogSummary,
) -> str:
    """Render notebook data catalog as Markdown."""

    lines = [
        "# Notebook Data Catalog Report",
        "",
        "## Summary",
        "",
        f"- Assets cataloged: {summary.asset_count}",
        f"- Available assets: {summary.available_count}",
        f"- Explorable assets: {summary.explorable_count}",
        f"- Missing assets: {summary.missing_count}",
        f"- Blocking EDA assets: {summary.blocking_eda_count}",
        f"- Ready for initial EDA: {summary.ready_for_eda}",
        "",
        "## Assets",
        "",
        "| Asset | Category | Path | Required for EDA | Status | Rows | Size Bytes |",
        "|---|---|---|---:|---|---:|---:|",
    ]

    for entry in summary.entries:
        lines.append(
            "| "
            f"{entry.asset.label} | "
            f"{entry.asset.category} | "
            f"{entry.asset.relative_path} | "
            f"{entry.asset.required_for_eda} | "
            f"{entry.status} | "
            f"{entry.row_count if entry.row_count is not None else '-'} | "
            f"{entry.file_size_bytes} |"
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
        ]
    )

    if summary.ready_for_eda:
        lines.append("The available assets are enough to start initial notebook-based EDA.")
    else:
        lines.append("Initial EDA should wait until all required EDA assets are available.")

    lines.extend(
        [
            "",
            "## Training Note",
            "",
            (
                "A model-ready training table is cataloged but not required for initial "
                "EDA. Real ML training should still wait until the training table is "
                "schema-valid, non-empty, and documented."
            ),
        ]
    )

    return "\n".join(lines).rstrip() + "\n"


def write_notebook_data_catalog_report(
    summary: NotebookDataCatalogSummary,
    output_path: Path,
) -> Path:
    """Write notebook data catalog report."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_notebook_data_catalog_report(summary),
        encoding="utf-8",
    )
    return output_path
